"use client"

import { useMemo, useState } from 'react'
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, BadgeCheck, Banknote, BarChart3, Bot, CalendarDays, CheckCircle2, ChevronRight, CircleAlert, Clock3, ExternalLink, MessageSquareText, Package, Search, ShieldCheck, ShoppingBag, Store, Users, X } from 'lucide-react'

type Data = {
    adminEmail: string; databaseHasErrors:boolean; recentAdminActions:any[]
    metrics: { businesses:number; proBusinesses:number; newBusinesses7d:number; activeProducts:number; staleStock:number; views7d:number; viewsPrior7d:number; views30d:number; pendingOrders:number; bookings7d:number; pendingVerifications:number; pendingFeedback:number; assistantEvents30d:number; paidCount:number; revenueNaira:number; failedPayments:number; marketingTrend:{label:string;count:number}[]; marketingSources:{source:string;count:number}[]; maxSource:number }
    recentMerchants: any[]; recentFeedback: any[]; pendingOrders: any[]; pendingVerifications: any[]; upcomingBookings:any[]; staleProducts:any[]; referralsCount:number
}
const money = (n:number) => `₦${Math.round(n).toLocaleString('en-NG')}`
function wa(value?:string|null){if(!value)return undefined;let digits=value.replace(/\D/g,'');if(digits.startsWith('0'))digits=`234${digits.slice(1)}`;else if(digits.length===10)digits=`234${digits}`;return digits.length>=11?`https://wa.me/${digits}`:undefined}
const date = (v:string) => new Date(v).toLocaleDateString('en-NG',{day:'numeric',month:'short'})
const sections = [['Overview','overview'],['Businesses','businesses'],['Catalog health','catalog'],['Orders & bookings','operations'],['Growth & money','growth'],['Support','support']] as const

export function NimdaDashboard({data}:{data:Data}) {
    const [active,setActive]=useState('overview')
    const [query,setQuery]=useState('')
    const [mobileNav,setMobileNav]=useState(false)
    const [logout,setLogout]=useState(false)
    const [actionError,setActionError]=useState('')
    const [savingId,setSavingId]=useState('')
    const filtered=useMemo(()=>data.recentMerchants.filter(m=>`${m.business_name||''} ${m.email||''} ${m.business_slug||''}`.toLowerCase().includes(query.toLowerCase())),[query,data.recentMerchants])
    const m=data.metrics
    const attention=[
        {label:'Orders to review',value:m.pendingOrders,icon:ShoppingBag,href:'#operations',tone:'orange'},
        {label:'Bookings this week',value:m.bookings7d,icon:CalendarDays,href:'#operations',tone:'blue'},
        {label:'Businesses to verify',value:m.pendingVerifications,icon:ShieldCheck,href:'#businesses',tone:'violet'},
        {label:'Messages to answer',value:m.pendingFeedback,icon:MessageSquareText,href:'#support',tone:'rose'},
    ]
    async function updateItem(kind:'verification'|'feedback',id:string,status:string){setSavingId(id);setActionError('');try{const response=await fetch('/nimda/api/operations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,id,status})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save the change.');window.location.reload()}catch(error){setActionError(error instanceof Error?error.message:'Could not save the change.')}finally{setSavingId('')}}
    async function signOut(){setLogout(true); await fetch('/nimda/api/logout',{method:'POST'});window.location.assign('/')}
    return <div className="nimda-shell">
        <aside className={`nimda-sidebar ${mobileNav?'is-open':''}`}>
            <a href="#overview" className="nimda-brand"><span>Q</span><b>Qriblo</b><small>ADMIN</small></a>
            <p className="nimda-side-label">YOUR CONTROL ROOM</p>
            <nav>{sections.map(([label,id],i)=><button key={id} onClick={()=>{setActive(id);setMobileNav(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}} className={active===id?'active':''}><span>{i===0?<Activity/>:i===1?<Store/>:i===2?<Package/>:i===3?<ShoppingBag/>:i===4?<BarChart3/>:<MessageSquareText/>}</span>{label}{id==='support'&&m.pendingFeedback>0?<i>{m.pendingFeedback}</i>:null}</button>)}</nav>
            <div className="nimda-sidebar-bottom"><div><span className="nimda-online"/>Admin access on</div><small>{data.adminEmail}</small><button onClick={signOut} disabled={logout}>Sign out</button><a href="/" target="_blank" rel="noreferrer">View public site <ExternalLink size={13}/></a></div>
        </aside>
        {mobileNav&&<button className="nimda-backdrop" aria-label="Close menu" onClick={()=>setMobileNav(false)}/>}
        <main className="nimda-main">
            <header className="nimda-topbar"><button className="nimda-mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="Menu">☰</button><div className="nimda-breadcrumb">Qriblo <ChevronRight size={14}/><b>{sections.find(x=>x[1]===active)?.[0]}</b></div><div className="nimda-top-actions"><span className="nimda-today">{new Date().toLocaleDateString('en-NG',{weekday:'long',day:'numeric',month:'long'})}</span><span className="nimda-avatar">{data.adminEmail.slice(0,1).toUpperCase()}</span></div></header>
            <div className="nimda-content">
                {data.databaseHasErrors&&<div className="nimda-db-warning" role="alert"><CircleAlert/><span><b>Some dashboard data could not be loaded.</b> Numbers may be incomplete. Refresh or check the Supabase connection and access.</span></div>}
                <section id="overview" className="nimda-section nimda-welcome"><div><p className="nimda-eyebrow"><span/> THE DAILY PICTURE</p><h1>Good morning, team.</h1><p>Here’s what needs attention and how Qriblo is growing today.</p></div><div className="nimda-welcome-chip"><span>LIVE FROM YOUR DATABASE</span><b>{m.businesses.toLocaleString()} businesses</b><small>Updated just now</small></div></section>
                <section className="nimda-attention"><div className="nimda-section-heading"><div><p className="nimda-eyebrow">START HERE</p><h2>Needs attention</h2></div><span>Act on these first</span></div><div className="nimda-attention-grid">{attention.map(item=><a key={item.label} href={item.href} className={`nimda-attention-card ${item.tone}`}><item.icon/><div><b>{item.value}</b><span>{item.label}</span></div><ArrowRight/></a>)}</div></section>
                <section className="nimda-section" id="growth"><div className="nimda-section-heading"><div><p className="nimda-eyebrow">BUSINESS HEALTH</p><h2>At a glance</h2></div><span>Compared with the previous 7 days</span></div><div className="nimda-kpi-grid">
                    <article><span className="nimda-kpi-icon wine"><Store/></span><small>All businesses</small><b>{m.businesses.toLocaleString()}</b><em>{m.newBusinesses7d} joined in 7 days</em></article>
                    <article><span className="nimda-kpi-icon green"><BadgeCheck/></span><small>Pro businesses</small><b>{m.proBusinesses.toLocaleString()}</b><em>{m.businesses?Math.round(m.proBusinesses/m.businesses*100):0}% of all businesses</em></article>
                    <article><span className="nimda-kpi-icon orange"><EyeIcon/></span><small>Page visits · 7 days</small><b>{m.views7d.toLocaleString()}</b><em className={m.views7d>=m.viewsPrior7d?'positive':'negative'}>{m.views7d>=m.viewsPrior7d?<ArrowUpRight/>:<ArrowDownRight/>}{m.viewsPrior7d?`${Math.round((m.views7d-m.viewsPrior7d)/m.viewsPrior7d*100)}%`:'No prior week data'} vs last week</em></article>
                    <article><span className="nimda-kpi-icon violet"><Package/></span><small>Active products & services</small><b>{m.activeProducts.toLocaleString()}</b><em>{m.staleStock.toLocaleString()} need stock checks</em></article>
                </div></section>
                <section id="operations" className="nimda-section nimda-grid-two"><article className="nimda-panel"><div className="nimda-panel-heading"><div><p className="nimda-eyebrow">SELLER OPERATIONS</p><h2>Open orders</h2></div><span className="nimda-count-pill">Seller follow-up</span></div>{data.pendingOrders.length?data.pendingOrders.map(order=><div className="nimda-list-row" key={order.id}><span className="nimda-list-icon orange"><ShoppingBag/></span><div><b>{order.customer_name||'Customer'}</b><small>{order.users?.business_name||'Seller'} · {money(Number(order.total_amount||0))} · {date(order.created_at)}</small></div>{order.users?.whatsapp_number&&<a href={wa(order.users.whatsapp_number)} target="_blank" rel="noreferrer">Seller <ExternalLink/></a>}<span className="nimda-status">Needs reply</span></div>):<div className="nimda-empty"><CheckCircle2/><b>No orders waiting</b><span>New requests will show here.</span></div>}<p className="nimda-panel-note">Use the seller’s WhatsApp link above to help move a pending request forward.</p></article><article className="nimda-panel"><div className="nimda-panel-heading"><div><p className="nimda-eyebrow">UPCOMING</p><h2>Bookings this week</h2></div><span className="nimda-count-pill">{m.bookings7d} total</span></div>{data.upcomingBookings.length?data.upcomingBookings.map(item=><div className="nimda-list-row" key={item.id}><span className="nimda-list-icon violet"><CalendarDays/></span><div><b>{item.customer_name} · {item.service_name}</b><small>{item.users?.business_name||'Business'} · {date(item.booking_date)} at {String(item.booking_time).slice(0,5)}</small></div></div>):<div className="nimda-empty"><CheckCircle2/><b>No bookings this week</b></div>}</article></section>
                <section id="catalog" className="nimda-section"><div className="nimda-catalog-alert"><div className="nimda-catalog-icon"><CircleAlert/></div><div><p className="nimda-eyebrow">CATALOG FRESHNESS</p><h2>{m.staleStock.toLocaleString()} items need an availability check</h2><p>These products are marked in stock, but the seller has not confirmed them in the last 14 days. Customers may see out-of-date availability.</p></div></div><article className="nimda-panel nimda-stale-list">{data.staleProducts.map(product=><div className="nimda-list-row" key={product.id}><span className="nimda-list-icon orange"><Package/></span><div><b>{product.name}</b><small>{product.users?.business_name||'Seller'} · last edited {date(product.updated_at)}</small></div><a href={product.users?.business_slug?`/${product.users.business_slug}`:'/directory'} target="_blank" rel="noreferrer">Seller page <ExternalLink/></a>{product.users?.whatsapp_number&&<a href={wa(product.users.whatsapp_number)} target="_blank" rel="noreferrer">Ask seller</a>}</div>)}<p className="nimda-panel-note">Availability should be confirmed by the seller. Qriblo admins do not mark seller stock as available.</p></article></section>
                <section id="businesses" className="nimda-section nimda-panel"><div className="nimda-panel-heading"><div><p className="nimda-eyebrow">MERCHANTS</p><h2>Latest businesses</h2></div><label className="nimda-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a business or email"/></label></div><div className="nimda-table-wrap"><table className="nimda-table"><thead><tr><th>Business</th><th>Plan</th><th>Joined</th><th>Verification</th><th>Open</th></tr></thead><tbody>{filtered.map(b=><tr key={b.id}><td><b>{b.business_name||'Business name missing'}</b><small>{b.email} · qriblo.com/{b.business_slug||'no-link-yet'}</small></td><td><span className={`nimda-plan ${b.plan==='pro'?'pro':''}`}>{b.plan==='pro'?'PRO':'FREE'}</span></td><td>{date(b.created_at)}</td><td>{b.verification_status==='approved'?<span className="nimda-good">Verified</span>:b.verification_status==='pending'?<span className="nimda-pending">Needs review</span>:<span className="nimda-muted">Not verified</span>}</td><td><a href={b.business_slug?`/${b.business_slug}`:'/dashboard'} target="_blank" rel="noreferrer">View <ExternalLink/></a></td></tr>)}</tbody></table>{!filtered.length&&<div className="nimda-empty">No businesses match that search.</div>}</div><p className="nimda-panel-note">{data.referralsCount} businesses have joined the referral program. Payouts should be checked against payment and eligibility records.</p></section>
                <section className="nimda-section nimda-grid-two"><article className="nimda-panel"><div className="nimda-panel-heading"><div><p className="nimda-eyebrow">VERIFY SELLERS</p><h2>Businesses to review</h2></div><span className="nimda-count-pill">{m.pendingVerifications}</span></div>{data.pendingVerifications.length?data.pendingVerifications.map(item=><div className="nimda-list-row" key={item.id}><span className="nimda-list-icon violet"><ShieldCheck/></span><div><b>{item.business_name||'Business name missing'}</b><small>{item.email} · joined {date(item.created_at)}</small></div>{item.verification_document_url&&<a href={item.verification_document_url} target="_blank" rel="noreferrer">View ID <ExternalLink/></a>}<button disabled={savingId===item.id} onClick={()=>updateItem('verification',item.id,'approved')}>Approve</button><button disabled={savingId===item.id} onClick={()=>updateItem('verification',item.id,'rejected')}>Reject</button></div>):<div className="nimda-empty"><CheckCircle2/><b>No businesses waiting for verification</b></div>}</article><article className="nimda-panel"><div className="nimda-panel-heading"><div><p className="nimda-eyebrow">CUSTOMER SUPPORT</p><h2>Feedback to review</h2></div><span className="nimda-count-pill">{m.pendingFeedback}</span></div>{actionError&&<p className="nimda-form-error" role="alert">{actionError}</p>}{data.recentFeedback.length?data.recentFeedback.map(item=><div className="nimda-feedback" key={item.id}><div><span className="nimda-feedback-type">{item.type}</span><small>{date(item.created_at)}</small></div><p>{item.message}</p><div className="nimda-feedback-actions"><button disabled={savingId===item.id} onClick={()=>updateItem('feedback',item.id,'reviewed')}>Mark reviewed</button><button disabled={savingId===item.id} onClick={()=>updateItem('feedback',item.id,'resolved')}>Resolve</button></div></div>):<div className="nimda-empty"><CheckCircle2/><b>Inbox is clear</b></div>}<a className="nimda-panel-footer" href="mailto:qriblovirtual@gmail.com">Contact support inbox <ArrowRight/></a></article></section>
                <section className="nimda-section nimda-panel nimda-marketing"><div className="nimda-panel-heading"><div><p className="nimda-eyebrow">MARKETING · LAST 14 DAYS</p><h2>Where customers come from</h2></div><span>{m.views30d.toLocaleString()} page visits in 30 days</span></div><div className="nimda-bars">{m.marketingTrend.map((day,index)=><div key={`${day.label}-${index}`} title={`${day.count} visits`}><i style={{height:`${Math.max(4,day.count/Math.max(1,...m.marketingTrend.map(item=>item.count))*100)}%`}}/><small>{day.label}</small></div>)}</div><div className="nimda-source-grid">{m.marketingSources.map(source=><div key={source.source}><span>{source.source}</span><div><i style={{width:`${Math.max(4,source.count/m.maxSource*100)}%`}}/></div><b>{source.count}</b></div>)}{!m.marketingSources.length&&<p className="nimda-panel-note">No page-visit sources recorded in the last 30 days.</p>}</div></section>
                <section className="nimda-section nimda-grid-two"><article className="nimda-panel"><div className="nimda-panel-heading"><div><p className="nimda-eyebrow">REVENUE · 30 DAYS</p><h2>{money(m.revenueNaira)}</h2><small>From {m.paidCount} successful Paystack payments</small></div><span className="nimda-kpi-icon green"><Banknote/></span></div><div className="nimda-revenue-foot"><span><CheckCircle2/>{m.paidCount} successful</span><span className={m.failedPayments?'warning':''}><CircleAlert/>{m.failedPayments} failed</span></div></article><article className="nimda-panel"><div className="nimda-panel-heading"><div><p className="nimda-eyebrow">VIRTUAL ASSISTANT · 30 DAYS</p><h2>{m.assistantEvents30d.toLocaleString()} tracked actions</h2></div><span className="nimda-kpi-icon orange"><Bot/></span></div><p className="nimda-panel-note">{m.assistantEvents30d ? 'Inquiry and follow-up actions recorded in the last 30 days.' : 'No assistant actions were recorded in the last 30 days.'}</p><div className="nimda-assistant-stat">{m.views30d.toLocaleString()} page visits in the same period</div></article></section>
                <section className="nimda-section nimda-panel"><div className="nimda-panel-heading"><div><p className="nimda-eyebrow">TEAM AUDIT</p><h2>Recent admin changes</h2></div><span>Last 8 actions</span></div>{data.recentAdminActions.length?data.recentAdminActions.map(item=><div className="nimda-list-row" key={item.id}><span className="nimda-list-icon violet"><ShieldCheck/></span><div><b>{item.action.replaceAll('_',' ')}</b><small>{item.admin_email} · {date(item.created_at)}</small></div></div>):<div className="nimda-empty"><Activity/><b>No admin changes yet</b></div>}</section>
                <section id="support" className="nimda-section nimda-bottom-note"><Clock3/><span><b>Daily team rhythm:</b> review orders and bookings, verify sellers, follow up on support, then check catalog freshness and weekly growth.</span></section>
                <footer className="nimda-footer">Qriblo Admin <span/> Clear view. Better decisions. <a href="mailto:qriblovirtual@gmail.com">Get help</a></footer>
            </div>
        </main>
    </div>
}
function EyeIcon(){return <Activity/>}
